repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-private-key
  - id: check-json
  - id: check-yaml
    args:
     - --unsafe

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.19.2
  hooks:
    - id: check-github-workflows
    - id: check-github-actions
    - id: check-dependabot
